// ET Sniper — License Server v3
// Two-tier access: superadmin (you) + panel users (can't create keys or users)
// Discord bot: generates keys via slash commands, owner role only, your server only

const express = require('express');
const jwt     = require('jsonwebtoken');
const crypto  = require('crypto');
const fs      = require('fs');
const path    = require('path');
const { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder, EmbedBuilder } = require('discord.js');

const app  = express();
const PORT = process.env.PORT || 3000;

const JWT_SECRET      = process.env.JWT_SECRET;
const ADMIN_KEY       = process.env.ADMIN_KEY;
const DISCORD_TOKEN   = process.env.DISCORD_TOKEN;    // your bot token
const DISCORD_GUILD   = process.env.DISCORD_GUILD;    // your server ID
const DISCORD_ROLE    = process.env.DISCORD_ROLE;     // owner role ID allowed to gen keys

if (!JWT_SECRET) { console.error('FATAL: JWT_SECRET not set'); process.exit(1); }
if (!ADMIN_KEY)  { console.error('FATAL: ADMIN_KEY not set');  process.exit(1); }

// ── DISCORD BOT ───────────────────────────────────────────────────────────
if (DISCORD_TOKEN && DISCORD_GUILD && DISCORD_ROLE) {

  const client = new Client({ intents: [GatewayIntentBits.Guilds] });

  // Register slash commands
  const commands = [
    new SlashCommandBuilder()
      .setName('genkey')
      .setDescription('Generate a new TokenSnipe license key')
      .addStringOption(o => o.setName('note').setDescription('Who is this key for?').setRequired(false))
      .addStringOption(o => o.setName('duration').setDescription('How long? e.g. 7, 30, 90, lifetime').setRequired(false)),
    new SlashCommandBuilder()
      .setName('revokekey')
      .setDescription('Revoke a TokenSnipe license key')
      .addStringOption(o => o.setName('key').setDescription('The key to revoke e.g. ET-XXXXXXXXXXXXXXXX').setRequired(true)),
    new SlashCommandBuilder()
      .setName('keyinfo')
      .setDescription('Look up info on a license key')
      .addStringOption(o => o.setName('key').setDescription('The key to look up').setRequired(true)),
    new SlashCommandBuilder()
      .setName('resetwid')
      .setDescription('Reset the HWID lock on a key')
      .addStringOption(o => o.setName('key').setDescription('The key to reset').setRequired(true)),
    new SlashCommandBuilder()
      .setName('listkeys')
      .setDescription('List all active keys'),
  ].map(c => c.toJSON());

  client.once('ready', async () => {
    console.log(`Discord bot logged in as ${client.user.tag}`);
    try {
      const rest = new REST({ version: '10' }).setToken(DISCORD_TOKEN);
      await rest.put(Routes.applicationGuildCommands(client.user.id, DISCORD_GUILD), { body: commands });
      console.log('Discord slash commands registered');
    } catch (e) { console.error('Failed to register commands:', e); }
  });

  client.on('interactionCreate', async interaction => {
    if (!interaction.isChatInputCommand()) return;

    // Only works in your server
    if (interaction.guildId !== DISCORD_GUILD) {
      return interaction.reply({ content: 'This bot only works in the TokenSnipe server.', ephemeral: true });
    }

    // Check if user has the required role
    const member = interaction.member;
    const hasRole = member.roles.cache.has(DISCORD_ROLE);
    if (!hasRole) {
      return interaction.reply({ content: 'You need the owner role to use this command.', ephemeral: true });
    }

    const { commandName } = interaction;

    // ── /genkey ──────────────────────────────────────────────────────────
    if (commandName === 'genkey') {
      const note     = interaction.options.getString('note') || '';
      const duration = interaction.options.getString('duration') || 'lifetime';
      const key      = 'ET-' + crypto.randomBytes(8).toString('hex').toUpperCase();
      const keys     = loadKeys();
      const expiresAt = duration !== 'lifetime' && !isNaN(parseInt(duration))
        ? new Date(Date.now() + parseInt(duration) * 86400000).toISOString()
        : null;
      keys[key] = {
        active: true,
        created: new Date().toISOString(),
        note,
        days: duration,
        expiresAt,
        activations: 0,
        hwid: null,
        lastUsed: null,
        createdBy: interaction.user.tag,
      };
      saveKeys(keys);

      const embed = new EmbedBuilder()
        .setColor(0x10b981)
        .setTitle('Key Generated')
        .addFields(
          { name: 'Key', value: '`' + key + '`', inline: false },
          { name: 'Duration', value: expiresAt ? duration + ' days' : 'Lifetime', inline: true },
          { name: 'Note', value: note || 'None', inline: true },
          { name: 'Expires', value: expiresAt ? new Date(expiresAt).toLocaleDateString() : 'Never', inline: true }
        )
        .setFooter({ text: 'Generated by ' + interaction.user.tag })
        .setTimestamp();

      return interaction.reply({ embeds: [embed], ephemeral: true });
    }

    // ── /revokekey ───────────────────────────────────────────────────────
    if (commandName === 'revokekey') {
      const key  = interaction.options.getString('key').toUpperCase();
      const keys = loadKeys();
      if (!keys[key]) return interaction.reply({ content: 'Key not found: `' + key + '`', ephemeral: true });
      keys[key].active = false;
      saveKeys(keys);

      const embed = new EmbedBuilder()
        .setColor(0xef4444)
        .setTitle('Key Revoked')
        .setDescription('`' + key + '` has been revoked. The user will be kicked within 5 minutes.')
        .setFooter({ text: 'Revoked by ' + interaction.user.tag })
        .setTimestamp();

      return interaction.reply({ embeds: [embed], ephemeral: true });
    }

    // ── /keyinfo ─────────────────────────────────────────────────────────
    if (commandName === 'keyinfo') {
      const key   = interaction.options.getString('key').toUpperCase();
      const keys  = loadKeys();
      const entry = keys[key];
      if (!entry) return interaction.reply({ content: 'Key not found: `' + key + '`', ephemeral: true });

      const now    = new Date();
      const status = !entry.active ? 'Revoked' : (entry.expiresAt && new Date(entry.expiresAt) <= now) ? 'Expired' : 'Active';
      const color  = status === 'Active' ? 0x10b981 : 0xef4444;

      const embed = new EmbedBuilder()
        .setColor(color)
        .setTitle('Key Info: ' + key)
        .addFields(
          { name: 'Status', value: status, inline: true },
          { name: 'Note', value: entry.note || 'None', inline: true },
          { name: 'HWID', value: entry.hwid ? 'Locked' : 'Free', inline: true },
          { name: 'Expires', value: entry.expiresAt ? new Date(entry.expiresAt).toLocaleDateString() : 'Never', inline: true },
          { name: 'Uses', value: String(entry.activations || 0), inline: true },
          { name: 'Last Used', value: entry.lastUsed ? new Date(entry.lastUsed).toLocaleDateString() : 'Never', inline: true },
          { name: 'Created', value: new Date(entry.created).toLocaleDateString(), inline: true },
          { name: 'Created By', value: entry.createdBy || 'Dashboard', inline: true },
        )
        .setTimestamp();

      return interaction.reply({ embeds: [embed], ephemeral: true });
    }

    // ── /resetwid ────────────────────────────────────────────────────────
    if (commandName === 'resetwid') {
      const key  = interaction.options.getString('key').toUpperCase();
      const keys = loadKeys();
      if (!keys[key]) return interaction.reply({ content: 'Key not found: `' + key + '`', ephemeral: true });
      keys[key].hwid      = null;
      keys[key].lockedAt  = null;
      saveKeys(keys);

      const embed = new EmbedBuilder()
        .setColor(0xa78bfa)
        .setTitle('HWID Reset')
        .setDescription('`' + key + '` is now unlocked and can be activated on a new device.')
        .setFooter({ text: 'Reset by ' + interaction.user.tag })
        .setTimestamp();

      return interaction.reply({ embeds: [embed], ephemeral: true });
    }

    // ── /listkeys ────────────────────────────────────────────────────────
    if (commandName === 'listkeys') {
      const keys   = loadKeys();
      const now    = new Date();
      const active = Object.entries(keys).filter(([, v]) => v.active && (!v.expiresAt || new Date(v.expiresAt) > now));

      if (!active.length) return interaction.reply({ content: 'No active keys found.', ephemeral: true });

      const lines = active.slice(0, 20).map(([k, v]) => {
        const exp = v.expiresAt ? new Date(v.expiresAt).toLocaleDateString() : 'Lifetime';
        return '`' + k + '` — ' + (v.note || 'No note') + ' — ' + exp;
      });

      const embed = new EmbedBuilder()
        .setColor(0x3b82f6)
        .setTitle('Active Keys (' + active.length + ')')
        .setDescription(lines.join('\n') + (active.length > 20 ? '\n...and ' + (active.length - 20) + ' more' : ''))
        .setTimestamp();

      return interaction.reply({ embeds: [embed], ephemeral: true });
    }
  });

  client.login(DISCORD_TOKEN).catch(e => console.error('Discord login failed:', e));

} else {
  console.log('Discord bot disabled — set DISCORD_TOKEN, DISCORD_GUILD, DISCORD_ROLE to enable');
}

// ── DATABASES ─────────────────────────────────────────────────────────────
const KEYS_FILE  = path.join(__dirname, 'keys.json');
const USERS_FILE = path.join(__dirname, 'users.json'); // panel user accounts

function loadKeys()  { try { return JSON.parse(fs.readFileSync(KEYS_FILE,  'utf8')); } catch { return {}; } }
function saveKeys(k) { fs.writeFileSync(KEYS_FILE,  JSON.stringify(k, null, 2)); }
function loadUsers()  { try { return JSON.parse(fs.readFileSync(USERS_FILE, 'utf8')); } catch { return {}; } }
function saveUsers(u) { fs.writeFileSync(USERS_FILE, JSON.stringify(u, null, 2)); }

// ── MIDDLEWARE ────────────────────────────────────────────────────────────
app.use(express.json());
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Content-Type, x-et-token, x-hwid, x-admin-key, x-panel-token');
  res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  if (req.method === 'OPTIONS') return res.sendStatus(200);
  next();
});

// Rate limiter
const rlMap = new Map();
function rateLimit(key, max) {
  const now = Date.now();
  const e   = rlMap.get(key) || { count: 0, reset: now + 60000 };
  if (now > e.reset) { e.count = 0; e.reset = now + 60000; }
  e.count++; rlMap.set(key, e);
  return e.count > max;
}

// ── AUTH HELPERS ──────────────────────────────────────────────────────────

// Is this request from the superadmin?
function isSuperAdmin(req) {
  return (req.headers['x-admin-key'] || req.query.ak) === ADMIN_KEY;
}

// Require superadmin only
function requireSuperAdmin(req, res, next) {
  if (!isSuperAdmin(req)) return res.status(403).json({ error: 'Superadmin only' });
  next();
}

// Require superadmin OR a valid panel user token
function requirePanel(req, res, next) {
  if (isSuperAdmin(req)) { req.isSuperAdmin = true; return next(); }
  const tok = req.headers['x-panel-token'];
  if (!tok) return res.status(403).json({ error: 'Not authenticated' });
  try {
    const payload = jwt.verify(tok, JWT_SECRET + '_panel');
    const users   = loadUsers();
    if (!users[payload.username] || !users[payload.username].active)
      return res.status(403).json({ error: 'Panel account revoked' });
    req.panelUser    = payload.username;
    req.isSuperAdmin = false;
    next();
  } catch { return res.status(403).json({ error: 'Invalid panel token' }); }
}

// Extension token validation
function requireToken(req, res, next) {
  const token = req.headers['x-et-token'];
  const hwid  = req.headers['x-hwid'];
  if (!token) return res.status(401).json({ error: 'No token' });
  try {
    const payload = jwt.verify(token, JWT_SECRET);
    const keys    = loadKeys();
    const entry   = keys[payload.key];
    if (!entry || !entry.active) return res.status(401).json({ error: 'Key revoked' });
    if (entry.expiresAt && new Date() > new Date(entry.expiresAt)) return res.status(401).json({ error: 'Key expired' });
    if (entry.hwid && entry.hwid !== hwid) return res.status(401).json({ error: 'HWID mismatch' });
    req.keyPayload = payload;
    next();
  } catch { return res.status(401).json({ error: 'Invalid or expired token' }); }
}

// ── EXTENSION ROUTES ──────────────────────────────────────────────────────

app.post('/validate', (req, res) => {
  const { key, hwid } = req.body;
  if (!key || !hwid) return res.status(400).json({ valid: false, error: 'Missing fields' });
  const ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress;
  if (rateLimit(ip, 5)) return res.status(429).json({ valid: false, error: 'Too many attempts. Wait a minute.' });
  const keys  = loadKeys();
  const entry = keys[key];
  if (!entry || !entry.active) return res.json({ valid: false, error: 'Invalid or revoked key' });
  if (entry.expiresAt && new Date() > new Date(entry.expiresAt)) return res.json({ valid: false, error: 'Key has expired' });
  if (!entry.hwid) { entry.hwid = hwid; entry.lockedAt = new Date().toISOString(); }
  else if (entry.hwid !== hwid) return res.json({ valid: false, error: 'Key is locked to another device' });
  entry.lastUsed    = new Date().toISOString();
  entry.activations = (entry.activations || 0) + 1;
  saveKeys(keys);
  const token = jwt.sign({ key, hwid }, JWT_SECRET, { expiresIn: '7d' });
  res.json({ valid: true, token, expiresAt: entry.expiresAt || null, note: entry.note || '' });
});

app.get('/heartbeat', requireToken, (req, res) => {
  const keys  = loadKeys();
  const entry = keys[req.keyPayload.key];
  res.json({ ok: true, expiresAt: entry?.expiresAt || null, note: entry?.note || '' });
});

// ── PANEL LOGIN ───────────────────────────────────────────────────────────

// POST /panel/login — for panel users (not superadmin)
app.post('/panel/login', (req, res) => {
  const { username, password } = req.body;
  if (!username || !password) return res.status(400).json({ error: 'Missing fields' });
  const ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress;
  if (rateLimit('panel:' + ip, 5)) return res.status(429).json({ error: 'Too many attempts' });
  const users = loadUsers();
  const user  = users[username];
  if (!user || !user.active) return res.status(403).json({ error: 'Invalid credentials' });
  // Simple password hash check
  const hash = crypto.createHash('sha256').update(password + JWT_SECRET).digest('hex');
  if (hash !== user.passwordHash) return res.status(403).json({ error: 'Invalid credentials' });
  const token = jwt.sign({ username }, JWT_SECRET + '_panel', { expiresIn: '24h' });
  res.json({ ok: true, token, username });
});

// ── ADMIN API — panel-accessible (all logged-in users) ───────────────────

app.get('/admin/keys', requirePanel, (req, res) => res.json(loadKeys()));

app.post('/admin/keys/revoke', requirePanel, (req, res) => {
  const { key } = req.body;
  const keys = loadKeys();
  if (!keys[key]) return res.status(404).json({ error: 'Not found' });
  keys[key].active = false;
  saveKeys(keys);
  res.json({ ok: true });
});

app.post('/admin/keys/reactivate', requirePanel, (req, res) => {
  const { key } = req.body;
  const keys = loadKeys();
  if (!keys[key]) return res.status(404).json({ error: 'Not found' });
  keys[key].active = true;
  saveKeys(keys);
  res.json({ ok: true });
});

app.post('/admin/keys/reset-hwid', requirePanel, (req, res) => {
  const { key } = req.body;
  const keys = loadKeys();
  if (!keys[key]) return res.status(404).json({ error: 'Not found' });
  keys[key].hwid = null; keys[key].lockedAt = null;
  saveKeys(keys);
  res.json({ ok: true });
});

app.post('/admin/keys/delete', requirePanel, (req, res) => {
  const { key } = req.body;
  const keys = loadKeys();
  if (!keys[key]) return res.status(404).json({ error: 'Not found' });
  delete keys[key];
  saveKeys(keys);
  res.json({ ok: true });
});

// ── ADMIN API — superadmin only ───────────────────────────────────────────

app.post('/admin/keys/create', requireSuperAdmin, (req, res) => {
  const { note, days } = req.body;
  const key       = 'ET-' + crypto.randomBytes(8).toString('hex').toUpperCase();
  const keys      = loadKeys();
  const expiresAt = days && days !== 'lifetime'
    ? new Date(Date.now() + parseInt(days) * 86400000).toISOString()
    : null;
  keys[key] = { active: true, created: new Date().toISOString(), note: note || '', days: days || 'lifetime', expiresAt, activations: 0, hwid: null, lastUsed: null };
  saveKeys(keys);
  res.json({ key, expiresAt });
});

// Panel user management — superadmin only
app.get('/admin/users', requireSuperAdmin, (req, res) => {
  const users = loadUsers();
  // Strip password hashes before sending
  const safe = {};
  Object.entries(users).forEach(([u, v]) => { safe[u] = { active: v.active, created: v.created, note: v.note }; });
  res.json(safe);
});

app.post('/admin/users/create', requireSuperAdmin, (req, res) => {
  const { username, password, note } = req.body;
  if (!username || !password) return res.status(400).json({ error: 'Missing fields' });
  const users = loadUsers();
  if (users[username]) return res.status(400).json({ error: 'Username already exists' });
  const hash = crypto.createHash('sha256').update(password + JWT_SECRET).digest('hex');
  users[username] = { active: true, created: new Date().toISOString(), note: note || '', passwordHash: hash };
  saveUsers(users);
  res.json({ ok: true });
});

app.post('/admin/users/revoke', requireSuperAdmin, (req, res) => {
  const { username } = req.body;
  const users = loadUsers();
  if (!users[username]) return res.status(404).json({ error: 'Not found' });
  users[username].active = false;
  saveUsers(users);
  res.json({ ok: true });
});

app.post('/admin/users/delete', requireSuperAdmin, (req, res) => {
  const { username } = req.body;
  const users = loadUsers();
  if (!users[username]) return res.status(404).json({ error: 'Not found' });
  delete users[username];
  saveUsers(users);
  res.json({ ok: true });
});

// ── ADMIN DASHBOARD ───────────────────────────────────────────────────────
app.get('/admin', (req, res) => {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Content-Security-Policy', "default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:;");
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ET Sniper Admin</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
:root{--bg:#07090f;--surf:#0e1420;--card:#131c2e;--border:rgba(59,130,246,0.15);--bhi:rgba(59,130,246,0.3);--blue:#3b82f6;--blt:#60a5fa;--t1:#f1f5f9;--t2:#94a3b8;--t3:#475569;--green:#10b981;--red:#ef4444;--gold:#f59e0b;--purple:#a78bfa}
body{background:var(--bg);color:var(--t1);font-family:'Segoe UI',system-ui,sans-serif;font-size:13px;min-height:100vh}
#login{display:flex;align-items:center;justify-content:center;min-height:100vh;padding:20px}
.login-box{background:var(--surf);border:1px solid var(--border);border-radius:16px;padding:36px;width:100%;max-width:380px;display:flex;flex-direction:column;gap:14px;text-align:center}
.login-box h1{font-size:20px;font-weight:700}
.login-tabs{display:flex;gap:6px;margin-bottom:2px}
.ltab{flex:1;padding:7px;border-radius:8px;font-size:12px;font-weight:600;font-family:inherit;cursor:pointer;border:1px solid var(--border);background:transparent;color:var(--t3);transition:all .15s}
.ltab.on{background:rgba(59,130,246,.12);border-color:var(--bhi);color:var(--blt)}
input,select{width:100%;padding:9px 13px;background:var(--card);border:1px solid var(--border);border-radius:8px;color:var(--t1);font-size:13px;font-family:inherit;outline:none;transition:border-color .15s}
input:focus{border-color:var(--bhi)}
select option{background:var(--card)}
#app{display:none;flex-direction:column;min-height:100vh}
.topbar{background:var(--surf);border-bottom:1px solid var(--border);padding:12px 24px;display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:10}
.topbar-l{display:flex;align-items:center;gap:10px}
.topbar h1{font-size:15px;font-weight:700}
.role-badge{font-size:10px;padding:2px 8px;border-radius:20px;font-weight:700}
.role-badge.super{background:rgba(234,179,8,.12);border:1px solid rgba(234,179,8,.3);color:var(--gold)}
.role-badge.panel{background:rgba(59,130,246,.1);border:1px solid var(--border);color:var(--blt)}
.main{padding:20px 24px;display:flex;flex-direction:column;gap:16px;max-width:1200px;margin:0 auto;width:100%}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px}
.stat{background:var(--surf);border:1px solid var(--border);border-radius:10px;padding:14px 16px}
.stat-val{font-size:26px;font-weight:700;margin-bottom:2px}
.stat-label{font-size:10px;color:var(--t3);text-transform:uppercase;letter-spacing:.06em}
.card{background:var(--surf);border:1px solid var(--border);border-radius:12px;overflow:hidden}
.card-header{padding:12px 16px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}
.card-header h2{font-size:11px;font-weight:700;color:var(--t3);text-transform:uppercase;letter-spacing:.08em}
.card-body{padding:16px}
.row{display:flex;gap:8px;flex-wrap:wrap;align-items:flex-end}
.field{display:flex;flex-direction:column;gap:4px}
.field label{font-size:10px;color:var(--t3);font-weight:600;text-transform:uppercase;letter-spacing:.06em}
.field input,.field select{min-width:150px}
.search{padding:6px 12px;background:var(--card);border:1px solid var(--border);border-radius:7px;color:var(--t1);font-size:12px;font-family:inherit;outline:none;width:220px}
table{width:100%;border-collapse:collapse}
th{padding:8px 12px;text-align:left;font-size:10px;font-weight:700;color:var(--t3);text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid var(--border);white-space:nowrap}
td{padding:9px 12px;border-bottom:1px solid rgba(59,130,246,0.05);font-size:12px;vertical-align:middle}
tr:last-child td{border-bottom:none}
tr:hover td{background:rgba(59,130,246,0.03)}
.key-mono{font-family:monospace;font-size:12px;color:var(--blt);font-weight:600;cursor:pointer}
.key-mono:hover{color:#93c5fd}
.badge{display:inline-flex;align-items:center;font-size:10px;font-weight:700;padding:2px 8px;border-radius:20px;white-space:nowrap}
.badge.active{background:rgba(16,185,129,.1);border:1px solid rgba(16,185,129,.25);color:var(--green)}
.badge.revoked{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.25);color:var(--red)}
.badge.expired{background:rgba(245,158,11,.1);border:1px solid rgba(245,158,11,.25);color:var(--gold)}
.badge.locked{background:rgba(167,139,250,.1);border:1px solid rgba(167,139,250,.25);color:var(--purple)}
.badge.free{background:rgba(100,116,139,.1);border:1px solid rgba(100,116,139,.2);color:var(--t3)}
.actions{display:flex;gap:4px;flex-wrap:wrap}
button{padding:5px 12px;border-radius:6px;font-size:11px;font-weight:600;font-family:inherit;cursor:pointer;border:1px solid;transition:all .15s;white-space:nowrap}
.btn-primary{padding:9px 20px;background:linear-gradient(135deg,#1e40af,#3b82f6);border-color:var(--bhi);color:#fff;font-size:12px;border-radius:8px}
.btn-primary:hover{opacity:.9}
.btn-revoke{background:rgba(239,68,68,.08);border-color:rgba(239,68,68,.3);color:#f87171}
.btn-revoke:hover{background:rgba(239,68,68,.2)}
.btn-activate{background:rgba(16,185,129,.08);border-color:rgba(16,185,129,.3);color:var(--green)}
.btn-activate:hover{background:rgba(16,185,129,.2)}
.btn-hwid{background:rgba(167,139,250,.08);border-color:rgba(167,139,250,.3);color:var(--purple)}
.btn-hwid:hover{background:rgba(167,139,250,.2)}
.btn-delete{background:rgba(239,68,68,.04);border-color:rgba(100,116,139,.2);color:var(--t3)}
.btn-delete:hover{background:rgba(239,68,68,.15);color:#f87171}
.btn-logout{background:transparent;border-color:var(--border);color:var(--t3)}
.btn-logout:hover{border-color:rgba(239,68,68,.3);color:#f87171}
.ftab{background:transparent;border:1px solid var(--border);color:var(--t3);border-radius:20px;padding:3px 12px;font-size:11px}
.ftab.on{background:rgba(59,130,246,.1);border-color:var(--bhi);color:var(--blt)}
.note-col{color:var(--t2);max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.expiry-ok{color:var(--green)}.expiry-soon{color:var(--gold)}.expiry-exp{color:var(--red)}.expiry-never{color:var(--t3)}
.new-key-box{margin-top:12px;padding:10px 14px;background:rgba(16,185,129,0.06);border:1px solid rgba(16,185,129,0.2);border-radius:8px;display:none}
.new-key-box p{font-size:10px;color:var(--t3);margin-bottom:4px}
.new-key-val{font-family:monospace;font-size:15px;color:var(--green);font-weight:700;cursor:pointer}
.superonly{display:none}
.toast{position:fixed;bottom:20px;right:20px;padding:10px 18px;background:var(--card);border:1px solid var(--border);border-radius:10px;font-size:12px;font-weight:600;z-index:100;animation:tin .2s ease;pointer-events:none}
.toast.ok{border-color:rgba(16,185,129,.4);color:var(--green)}
.toast.err{border-color:rgba(239,68,68,.4);color:var(--red)}
@keyframes tin{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
.empty-row td{text-align:center;padding:32px;color:var(--t3)}
.divider{height:1px;background:var(--border);margin:4px 0}
</style>
</head>
<body>

<div id="login">
  <div class="login-box">
    <div>
      <div style="font-size:32px;margin-bottom:8px">🔑</div>
      <h1>ET Sniper Admin</h1>
      <p style="color:var(--t3);font-size:12px;margin-top:4px">Sign in to manage keys</p>
    </div>
    <div class="login-tabs">
      <button class="ltab on" id="tab-admin" onclick="switchLoginTab('admin')">Superadmin</button>
      <button class="ltab" id="tab-panel" onclick="switchLoginTab('panel')">Panel User</button>
    </div>
    <div id="login-admin">
      <input id="ak" type="password" placeholder="Admin key..." />
    </div>
    <div id="login-panel" style="display:none;display:flex;flex-direction:column;gap:8px">
      <input id="pu-user" type="text" placeholder="Username" autocomplete="off" />
      <input id="pu-pass" type="password" placeholder="Password" />
    </div>
    <button class="btn-primary" onclick="doLogin()">Login</button>
    <div id="lerr" style="color:var(--red);font-size:11px;min-height:14px"></div>
  </div>
</div>

<div id="app">
  <div class="topbar">
    <div class="topbar-l">
      <h1>ET Sniper</h1>
      <span class="role-badge super" id="role-badge">Superadmin</span>
    </div>
    <div style="display:flex;align-items:center;gap:8px">
      <span id="whoami" style="font-size:11px;color:var(--t3)"></span>
      <button class="btn-logout" onclick="logout()">Logout</button>
    </div>
  </div>

  <div class="main">
    <!-- Stats -->
    <div class="stats">
      <div class="stat"><div class="stat-val" id="s-total" style="color:var(--blt)">0</div><div class="stat-label">Total Keys</div></div>
      <div class="stat"><div class="stat-val" id="s-active" style="color:var(--green)">0</div><div class="stat-label">Active</div></div>
      <div class="stat"><div class="stat-val" id="s-revoked" style="color:var(--red)">0</div><div class="stat-label">Revoked</div></div>
      <div class="stat"><div class="stat-val" id="s-expired" style="color:var(--gold)">0</div><div class="stat-label">Expired</div></div>
      <div class="stat"><div class="stat-val" id="s-uses" style="color:var(--purple)">0</div><div class="stat-label">Total Uses</div></div>
    </div>

    <!-- Create key — superadmin only -->
    <div class="card superonly" id="create-key-card">
      <div class="card-header"><h2>Generate New Key</h2></div>
      <div class="card-body">
        <div class="row">
          <div class="field"><label>Note / Username</label><input id="c-note" type="text" placeholder="e.g. Discord user xyz" /></div>
          <div class="field">
            <label>Duration</label>
            <select id="c-days">
              <option value="1">1 day</option><option value="3">3 days</option>
              <option value="7">7 days</option><option value="14">14 days</option>
              <option value="30">30 days</option><option value="90">90 days</option>
              <option value="180">6 months</option><option value="365">1 year</option>
              <option value="lifetime" selected>Lifetime</option>
            </select>
          </div>
          <button class="btn-primary" onclick="createKey()">+ Generate Key</button>
        </div>
        <div class="new-key-box" id="new-key-box">
          <p>New key created — click to copy:</p>
          <div class="new-key-val" id="new-key-val"></div>
        </div>
      </div>
    </div>

    <!-- Panel users — superadmin only -->
    <div class="card superonly" id="users-card">
      <div class="card-header"><h2>Panel Users</h2></div>
      <div class="card-body">
        <div class="row" style="margin-bottom:12px">
          <div class="field"><label>Username</label><input id="u-name" type="text" placeholder="username" autocomplete="off" /></div>
          <div class="field"><label>Password</label><input id="u-pass" type="text" placeholder="password" /></div>
          <div class="field"><label>Note</label><input id="u-note" type="text" placeholder="optional note" /></div>
          <button class="btn-primary" onclick="createUser()">+ Add User</button>
        </div>
        <div style="overflow-x:auto">
          <table>
            <thead><tr><th>Username</th><th>Note</th><th>Status</th><th>Actions</th></tr></thead>
            <tbody id="users-body"></tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Keys table — everyone -->
    <div class="card">
      <div class="card-header">
        <h2>All Keys</h2>
        <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">
          <div style="display:flex;gap:4px">
            <button class="ftab on" onclick="setFilter('all',this)">All</button>
            <button class="ftab" onclick="setFilter('active',this)">Active</button>
            <button class="ftab" onclick="setFilter('revoked',this)">Revoked</button>
            <button class="ftab" onclick="setFilter('expired',this)">Expired</button>
          </div>
          <input class="search" type="text" id="search" placeholder="Search key or note..." oninput="renderTable()" />
        </div>
      </div>
      <div style="overflow-x:auto">
        <table>
          <thead><tr><th>Key</th><th>Note</th><th>Status</th><th>HWID</th><th>Expires</th><th>Uses</th><th>Last Used</th><th>Actions</th></tr></thead>
          <tbody id="keys-body"></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
let adminKey='', panelToken='', isSuperAdmin=false, whoami='';
let keysData={}, usersData={}, filterMode='all', loginTab='admin';

function switchLoginTab(tab){
  loginTab=tab;
  document.getElementById('tab-admin').classList.toggle('on', tab==='admin');
  document.getElementById('tab-panel').classList.toggle('on', tab==='panel');
  document.getElementById('login-admin').style.display = tab==='admin'?'block':'none';
  document.getElementById('login-panel').style.display = tab==='panel'?'flex':'none';
}
switchLoginTab('admin');

async function doLogin(){
  document.getElementById('lerr').textContent='';
  if(loginTab==='admin'){
    adminKey=document.getElementById('ak').value.trim();
    if(!adminKey)return;
    const ok=await fetchKeys(true);
    if(ok){ isSuperAdmin=true; whoami='Superadmin'; showApp(); }
    else{ document.getElementById('lerr').textContent='Invalid admin key.'; adminKey=''; }
  } else {
    const user=document.getElementById('pu-user').value.trim();
    const pass=document.getElementById('pu-pass').value.trim();
    if(!user||!pass)return;
    try{
      const res=await fetch('/panel/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user,password:pass})});
      const data=await res.json();
      if(data.ok){ panelToken=data.token; isSuperAdmin=false; whoami=user; const ok=await fetchKeys(false); if(ok)showApp(); }
      else document.getElementById('lerr').textContent=data.error||'Invalid credentials.';
    }catch{ document.getElementById('lerr').textContent='Connection error.'; }
  }
}
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.getElementById('login').style.display!=='none')doLogin();});

function showApp(){
  document.getElementById('login').style.display='none';
  document.getElementById('app').style.display='flex';
  document.getElementById('whoami').textContent=whoami;
  const badge=document.getElementById('role-badge');
  if(isSuperAdmin){ badge.textContent='Superadmin'; badge.className='role-badge super'; }
  else { badge.textContent='Panel User'; badge.className='role-badge panel'; }
  document.querySelectorAll('.superonly').forEach(el=>{ el.style.display=isSuperAdmin?'block':'none'; });
  if(isSuperAdmin) fetchUsers();
}

function logout(){
  adminKey=''; panelToken=''; isSuperAdmin=false; whoami=''; keysData={}; usersData={};
  document.getElementById('login').style.display='flex';
  document.getElementById('app').style.display='none';
  document.getElementById('ak').value='';
  document.getElementById('pu-user').value='';
  document.getElementById('pu-pass').value='';
}

function getHeaders(){
  const h={'Content-Type':'application/json'};
  if(isSuperAdmin) h['x-admin-key']=adminKey;
  else h['x-panel-token']=panelToken;
  return h;
}

async function api(path,method='GET',body=null){
  const opts={method,headers:getHeaders()};
  if(body)opts.body=JSON.stringify(body);
  const res=await fetch(path,opts);
  return res.json();
}

async function fetchKeys(isAdmin){
  try{
    const headers={'Content-Type':'application/json'};
    if(isAdmin) headers['x-admin-key']=adminKey;
    else headers['x-panel-token']=panelToken;
    const res=await fetch('/admin/keys',{headers});
    const data=await res.json();
    if(data.error)return false;
    keysData=data; renderTable(); updateStats(); return true;
  }catch{return false;}
}

async function fetchUsers(){
  const data=await api('/admin/users');
  if(!data.error){ usersData=data; renderUsers(); }
}

function updateStats(){
  const vals=Object.values(keysData),now=new Date();
  document.getElementById('s-total').textContent=vals.length;
  document.getElementById('s-active').textContent=vals.filter(k=>k.active&&(!k.expiresAt||new Date(k.expiresAt)>now)).length;
  document.getElementById('s-revoked').textContent=vals.filter(k=>!k.active).length;
  document.getElementById('s-expired').textContent=vals.filter(k=>k.active&&k.expiresAt&&new Date(k.expiresAt)<=now).length;
  document.getElementById('s-uses').textContent=vals.reduce((a,k)=>a+(k.activations||0),0);
}

function setFilter(mode,el){ filterMode=mode; document.querySelectorAll('.ftab').forEach(b=>b.classList.remove('on')); el.classList.add('on'); renderTable(); }

function getStatus(k){ const now=new Date(); if(!k.active)return'revoked'; if(k.expiresAt&&new Date(k.expiresAt)<=now)return'expired'; return'active'; }

function fmtExpiry(k){
  if(!k.expiresAt)return'<span class="expiry-never">Lifetime</span>';
  const now=new Date(),exp=new Date(k.expiresAt),diff=exp-now,days=Math.ceil(diff/86400000),str=exp.toLocaleDateString();
  if(diff<=0)return'<span class="expiry-exp">'+str+' (expired)</span>';
  if(days<=3)return'<span class="expiry-soon">'+str+' ('+days+'d left)</span>';
  return'<span class="expiry-ok">'+str+'</span>';
}

function fmtDate(d){ if(!d)return'<span style="color:var(--t3)">Never</span>'; return new Date(d).toLocaleDateString()+' '+new Date(d).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}); }
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

function renderTable(){
  const search=document.getElementById('search').value.toLowerCase();
  const body=document.getElementById('keys-body');
  let entries=Object.entries(keysData);
  entries=entries.filter(([k,v])=>{
    const st=getStatus(v);
    if(filterMode!=='all'&&st!==filterMode)return false;
    if(search&&!k.toLowerCase().includes(search)&&!(v.note||'').toLowerCase().includes(search))return false;
    return true;
  });
  entries.sort((a,b)=>new Date(b[1].created)-new Date(a[1].created));
  if(!entries.length){body.innerHTML='<tr class="empty-row"><td colspan="8">No keys found</td></tr>';return;}
  body.innerHTML='';
  entries.forEach(([k,v])=>{
    const st=getStatus(v);
    const tr=document.createElement('tr');
    const hwidBadge=v.hwid?'<span class="badge locked">Locked</span>':'<span class="badge free">Free</span>';
    tr.innerHTML='<td><span class="key-mono" title="Click to copy">'+k+'</span></td>'
      +'<td><span class="note-col" title="'+esc(v.note||'')+'">'+esc(v.note||'-')+'</span></td>'
      +'<td><span class="badge '+st+'">'+st.charAt(0).toUpperCase()+st.slice(1)+'</span></td>'
      +'<td>'+hwidBadge+'</td>'
      +'<td>'+fmtExpiry(v)+'</td>'
      +'<td style="color:var(--purple)">'+(v.activations||0)+'</td>'
      +'<td style="color:var(--t3);font-size:11px">'+fmtDate(v.lastUsed)+'</td>'
      +'<td><div class="actions"></div></td>';
    tr.querySelector('.key-mono').addEventListener('click',()=>copyText(k));
    const acts=tr.querySelector('.actions');
    if(st==='revoked'){
      const b1=document.createElement('button');b1.className='btn-activate';b1.textContent='Reactivate';b1.onclick=()=>reactivate(k);acts.appendChild(b1);
      const b2=document.createElement('button');b2.className='btn-delete';b2.textContent='Delete';b2.onclick=()=>del(k);acts.appendChild(b2);
    }else{
      const b1=document.createElement('button');b1.className='btn-revoke';b1.textContent='Revoke';b1.onclick=()=>revoke(k);acts.appendChild(b1);
      if(v.hwid){const b2=document.createElement('button');b2.className='btn-hwid';b2.textContent='Reset HWID';b2.onclick=()=>resetHwid(k);acts.appendChild(b2);}
      const b3=document.createElement('button');b3.className='btn-delete';b3.textContent='Delete';b3.onclick=()=>del(k);acts.appendChild(b3);
    }
    body.appendChild(tr);
  });
}

function renderUsers(){
  const body=document.getElementById('users-body');
  const entries=Object.entries(usersData);
  if(!entries.length){body.innerHTML='<tr class="empty-row"><td colspan="4">No panel users yet</td></tr>';return;}
  body.innerHTML='';
  entries.forEach(([u,v])=>{
    const tr=document.createElement('tr');
    tr.innerHTML='<td style="font-weight:600">'+esc(u)+'</td>'
      +'<td style="color:var(--t2)">'+esc(v.note||'-')+'</td>'
      +'<td><span class="badge '+(v.active?'active':'revoked')+'">'+(v.active?'Active':'Revoked')+'</span></td>'
      +'<td><div class="actions"></div></td>';
    const acts=tr.querySelector('.actions');
    if(v.active){
      const b1=document.createElement('button');b1.className='btn-revoke';b1.textContent='Revoke';b1.onclick=()=>revokeUser(u);acts.appendChild(b1);
    }
    const b2=document.createElement('button');b2.className='btn-delete';b2.textContent='Delete';b2.onclick=()=>deleteUser(u);acts.appendChild(b2);
    body.appendChild(tr);
  });
}

async function createKey(){
  const note=document.getElementById('c-note').value.trim();
  const days=document.getElementById('c-days').value;
  const data=await api('/admin/keys/create','POST',{note,days});
  if(data.key){
    document.getElementById('new-key-box').style.display='block';
    const el=document.getElementById('new-key-val');
    el.textContent=data.key;
    el.onclick=()=>copyText(data.key);
    copyText(data.key);
    toast('Key created + copied!','ok');
    await fetchKeys(isSuperAdmin);
  }else toast(data.error||'Error creating key','err');
}

async function revoke(key){
  if(!confirm('Revoke '+key+'? User will be kicked within 5 min.'))return;
  const data=await api('/admin/keys/revoke','POST',{key});
  if(data.ok){toast('Key revoked','ok');await fetchKeys(isSuperAdmin);}else toast('Error','err');
}

async function reactivate(key){
  const data=await api('/admin/keys/reactivate','POST',{key});
  if(data.ok){toast('Key reactivated','ok');await fetchKeys(isSuperAdmin);}else toast('Error','err');
}

async function resetHwid(key){
  if(!confirm('Reset HWID for '+key+'? Key can be used on a new device.'))return;
  const data=await api('/admin/keys/reset-hwid','POST',{key});
  if(data.ok){toast('HWID reset','ok');await fetchKeys(isSuperAdmin);}else toast('Error','err');
}

async function del(key){
  if(!confirm('Permanently DELETE '+key+'? Cannot be undone.'))return;
  const data=await api('/admin/keys/delete','POST',{key});
  if(data.ok){toast('Key deleted','ok');await fetchKeys(isSuperAdmin);}else toast('Error','err');
}

async function createUser(){
  const username=document.getElementById('u-name').value.trim();
  const password=document.getElementById('u-pass').value.trim();
  const note=document.getElementById('u-note').value.trim();
  if(!username||!password){toast('Username and password required','err');return;}
  const data=await api('/admin/users/create','POST',{username,password,note});
  if(data.ok){
    toast('Panel user created!','ok');
    document.getElementById('u-name').value='';
    document.getElementById('u-pass').value='';
    document.getElementById('u-note').value='';
    await fetchUsers();
  }else toast(data.error||'Error','err');
}

async function revokeUser(username){
  if(!confirm('Revoke access for '+username+'?'))return;
  const data=await api('/admin/users/revoke','POST',{username});
  if(data.ok){toast('User revoked','ok');await fetchUsers();}else toast('Error','err');
}

async function deleteUser(username){
  if(!confirm('Delete panel user '+username+'?'))return;
  const data=await api('/admin/users/delete','POST',{username});
  if(data.ok){toast('User deleted','ok');await fetchUsers();}else toast('Error','err');
}

function copyText(t){navigator.clipboard.writeText(t).then(()=>toast('Copied!','ok'));}

let tTimer;
function toast(msg,type='ok'){
  const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;
  document.body.appendChild(el);clearTimeout(tTimer);tTimer=setTimeout(()=>el.remove(),2800);
}

setInterval(()=>{ if(adminKey||panelToken) fetchKeys(isSuperAdmin); },30000);
</script>
</body>
</html>`);
});

app.listen(PORT, () => console.log('ET Sniper server v3 running on port', PORT));
